const MEALS = {
    breakfast: [
        "Poha",
        "Upma",
        "Idli Sambar",
        "Dosa",
        "Paratha with Curd",
        "Omelette & Toast",
        "Pancakes",
        "Oats Porridge",
        "Bread & Jam",
        "Cereal & Milk",
    ],
    lunch: [
        "Dal Rice",
        "Rajma Chawal",
        "Chole Chawal",
        "Kadhi Chawal",
        "Roti Sabzi",
        "Biryani",
        "Fried Rice",
        "Khichdi",
        "Pasta",
        "Sandwich & Soup",
    ],
    dinner: [
        "Roti & Dal",
        "Paneer Butter Masala & Naan",
        "Egg Curry & Rice",
        "Soup & Salad",
        "Dosa & Chutney",
        "Pasta",
        "Stir Fry & Rice",
        "Paratha & Sabzi",
        "Khichdi",
        "Thali",
    ],
};
