const MEALS = {
    meal: [
        { name: "Bhindi", weight: 1 },
        { name: "Cauliflower", weight: 1 },
        { name: "Beans", weight: 0.5 },
        { name: "Palak", weight: 1 },
        { name: "Methi", weight: 1 },
        { name: "Drumstick", weight: 1 },
        { name: "Mushroom", weight: 0.5 },
        { name: "Paneer", weight: 1 },
        { name: "Egg Curry", weight: 1 },
        { name: "Egg Bhurji", weight: 1 },
        { name: "Rajma", weight: 1 },
        { name: "Chole", weight: 1 },
        { name: "Noodles", weight: 0.5 },
        { name: "Chicken Curry", weight: 1 },
        { name: "Fried Rice", weight: 1 },
        { name: "Alu Paratha", weight: 1 },
        { name: "Gobi Paratha", weight: 1 },
        { name: "Dosa", weight: 0.5 },
        { name: "Aloo Matar", weight: 1 },
        { name: "Dal Fry", weight: 1 },
        { name: "Kadhi Pakora", weight: 0.5 },
        { name: "Khichdi", weight: 1 },
        { name: "Soya Chunks", weight: 0.5 },
    ],
};
